### ISSUE TITLE
Action Flow のエラーについて

### ISSUE THREAD

**Issue by younosuke-n** [k5-mot/auto-hms-action#1]
3月3日、3月4日で4つ目のjobでエラーが起きているみたいです。
ですが、登録はちゃんとされています。
エラーの解決策になるかわかりませんが、1つ質問があります。
YAMLファイルでのフローの記述で最初の行でパッケージのアップデートを行っていますが、アップグレードを行わない理由は何でしょう？
ちなみに、エラーが発生する前日の3月2日は更新できるパッケージが56個、エラーが発生した初日での更新できるパッケージが57個と1個増えているのが、ログから確認できました。

**Comment by k5-mot** [comment]
- 3月3日、3月4日で4つ目のjobでエラーが起きているみたいです。
-- [コードを修正しました。](https://github.com/k5-mot/auto-hms-action/commit/a360d7c64f0cfc5903f4a2ebc16af9eab2a48989)
-- [動作確認もしました](https://github.com/k5-mot/auto-hms-action/runs/5433885432?check_suite_focus=true)

>>> YAMLファイルでのフローの記述で最初の行でパッケージのアップデートを行っていますが、アップグレードを行わない理由は何でしょう？
- アップグレードまですると、インストールまでして時間がかかりすぎてしまうので、やっていません。GitHub Actionsの無料枠は月当たり2,000時間なので、切り詰めて利用しています。
